### ISSUE TITLE
Use JSON API for newer versions of chromedriver

### ISSUE THREAD

**Issue by syamilmj** [schinckel/asdf-chromedriver#2]
With v115 and above, the drivers will no longer be published on the current API URL - https://chromedriver.storage.googleapis.com/LATEST_RELEASE. However, all chromedriver versions can be found on this JSON API endpoint - https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json

Would you be open to accept a PR that fetches the versions from this API endpoint?

More info here: https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints

**Comment by schinckel** [comment]
Absolutely

Matt.

**Comment by rolintoucour** [comment]
Hi @sax @schinckel  do you know if there is any workaround until you merge it?

**Comment by schinckel** [comment]
Hi there. I've merged this now, so you should be able to update the plugin and use the correct version.
